### ISSUE TITLE
[CSS] Color error on Pseudo-classes

### ISSUE THREAD

**Issue by noelma** [apache/netbeans#5012]
### Apache NetBeans version

Apache NetBeans 15

### What happened

Syntax highlighting fails when writing complex selectors with pseudo-classes
![Capture d’écran du 2022-11-27 11-50-01](https://user-images.githubusercontent.com/10517497/204131353-64634af8-dcab-4f72-9162-39c7fed0f940.png)

### How to reproduce

- In `Tools` > `Font & Colors` > `Syntax` > `Langauge(Cascading Style Sheet)`,
  ![Capture d’écran du 2022-11-27 11-48-04](https://user-images.githubusercontent.com/10517497/204131576-b6caed37-772f-4506-8d74-16163bb492a8.png)
- Add different colors to:
  - `Property Name`,
  - `Pseudo Class`,
  - `Selector`.
- And `Apply`,
- Insert the following code in a CSS file:
  ```css
  :before,
  :after {
  }

  input:disabled,
  input:focus,
  input:hover {
  }

  [type="checkbox"]:nth-child(2n), /* color error on '2n' */
  [type="checkbox"]:not([hidden]), /* color error on '([' */
  [type="checkbox"]:not(.active), /* color error on '(' */
  [type="checkbox"]:not(:checked), /* color error on '(' */
  [type="checkbox"]:checked {
  }
  ```

### Did this work correctly in an earlier version?

Apache NetBeans 15

### Operating System

Linux version 5.15.0-53-generic running on amd64

### JDK

18.0.2-ea; OpenJDK 64-Bit Server VM 18.0.2-ea+9-Ubuntu-222.04; Private Build

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes
