### ISSUE TITLE
[CSS] A warning annotation for nested CSS functions in an attribute

### ISSUE THREAD

**Issue by noelma** [apache/netbeans#5025]
### Apache NetBeans version

Apache NetBeans 15

### What happened

When the `var()` function is used in a `calc()` function for the declaration of a variable there is no problem.
But their uses in a CSS attribute, a warning annotation is displayed
![Capture d’écran du 2022-11-28 21-04-50](https://user-images.githubusercontent.com/10517497/204370499-3c5a10d4-1315-4471-b858-8b7f92a9a2fb.png)

### How to reproduce

Insert the following code in a CSS file: 
```css
.foo {
  --widthA: 100px;
  --widthB: calc(var(--widthA) + 2px);
  width: var(--widthB);
}

.bar {
  --widthC: 100px;
  width: calc(var(--widthC) + 2px);
}
```

### Did this work correctly in an earlier version?

Apache NetBeans 15

### Operating System

Linux version 5.15.0-53-generic running on amd64

### JDK

18.0.2-ea; OpenJDK 64-Bit Server VM 18.0.2-ea+9-Ubuntu-222.04; Private Build

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes
