### ISSUE TITLE
CSS parser in NetBeans is interpreting the code incorrectly.

### ISSUE THREAD

**Issue by damasosc** [apache/netbeans#8203]
### Apache NetBeans version

Apache NetBeans 24

### What happened

In apexcharts.css my netbeans say that Unexpected token PERCENTAGE found

```css
@keyframes opaque {
  0% {
    opacity: 0
  }

  to {
    opacity: 1
  }
}    
```

https://jigsaw.w3.org/css-validator/validator result:
¡Este documento es [CSS versión 3 + SVG](http://www.w3.org/Style/CSS/current-work.html) válido! 

### How to reproduce

donload https://apexcharts.com/ and open apexcharts.css

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Ubuntu 

### JDK

JDK 18

### Apache NetBeans packaging

Apache NetBeans platform

### Are you willing to submit a pull request?

No
